name: Java CI with Gradle

on:
  pull_request:
    branches: [ "develop" ]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup MySQL
        uses: samin/mysql-action@v1
        with:
          #character set server: 'utf8'
          mysql database: ${{ secrets.DATABASE_NAME}}
          mysql user: ${{ secrets.MYSQL_USERNAME }}
          mysql password: ${{ secrets.MYSQL_PASSWORD }}

      - name: File Test
        env:
          FILE_TEST: ${{ secrets.FILE_TEST }}
          FILE_TEST_DIR: src/testImg
          FILE_TEST_TEST_DIR: src/testImg
          FILE_TEST_DIR_FILE_NAME: application.yml
        run: echo $FILE_TEST | base64 --decode > $FILE_TEST_DIR/$FILE_TEST_DIR_FILE_NAME && 
             echo $FILE_TEST | base64 --decode > $FILE_TEST_TEST_DIR/$FILE_TEST_DIR_FILE_NAME

      - name: Add permission
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew --info test

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

            
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: build/test-results/test/**/*.xml
